version: "3.8"
services:
  mysqldb: 
    image: mysqldb
    build: .
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: geriatria
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - /mysql
